apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling-springboot
  template:
    metadata:
      labels:
        app: autoscaling-springboot
    spec:
      containers:
        - name: springboot-app
          image: autoscaling-springboot-eks:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
