apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling-springboot
  template:
    metadata:
      labels:
        app: autoscaling-springboot
    spec:
      containers:
        - name: springboot-app
          image: aasawarimongodb/autoscaling-springboot-eks:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-springboot-service
spec:
  selector:
    app: autoscaling-springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer